### ISSUE TITLE
[Question] Is is possible to export different assets depending on the target ?

### ISSUE THREAD

**Issue by amadeu01** [diez/diez#100]
I see that exists that target module `https://diez.org/docs/latest/modules/targets.html#onlytarget`.

But, my question is regarding how, if possible, to use the targets on the `DesignLanguage.ts`.

For instance:
```
const layoutValues = { 
  spacingSmall: 5,
  spacingMedium: 25,
  spacingLarge: 40,
  contentMargin: new Margin({
    top: 40,
    left: 10,
    right: 10,
    bottom: 10
  })
};
```

I would like the android version to have more spacings, like

```
const layoutValues = { 
  spacingSmall: 5,
  spacingSmallAndroid: 5, // only visible for android target
  spacingMedium: 25,
  spacingLarge: 40,
  contentMargin: new Margin({
    top: 40,
    left: 10,
    right: 10,
    bottom: 10
  })
};
```

Is there a way of doing this? Should we use the `@diez/target` module?

**Comment by roperzh** [comment]
Hey @amadeu01 ! the current way to specify a value for a specific target is by providing an `options` property, here you can define custom attributes for specific properties. In your example, this would be:

```ts
import {Target} from '@diez/engine';

const layoutValues = { 
  spacingSmall: 5,
  spacingSmallAndroid: 5, // only visible for android target
  spacingMedium: 25,
  spacingLarge: 40,
  contentMargin: new Margin({
    top: 40,
    left: 10,
    right: 10,
    bottom: 10
  }),
  
  // here you can provide specific options per property
  options: {
    // Tell Diez to only output `spacingSmallAndroid` for the `Android` target.
    spacingSmallAndroid: {
      targets: [Target.Android],
    },
  },
};

```

Let me know if you have any doubts! I think we should keep this issue open to create proper documentation about this in the diez guides.

**Comment by amadeu01** [comment]
@roperzh thanks !

**Comment by amadeu01** [comment]
@roperzh is it possible to update the docs on the website? to better explain how to add the target option?

**Comment by roperzh** [comment]
@amadeu01 yes, apologies I believe this repo should be more discoverable, the guides and the website are here: https://github.com/diez/www.diez.org

thanks for your contributions!
