### ISSUE TITLE
[Questions] - Json output? React Native?

### ISSUE THREAD

**Issue by arielwb** [diez/diez#115]
Hi!
I've been testing Diez and so far, very impressed! <3
I have a question: is it possible to generate a JSON output for the tokens? 
Like a stand alone JSON file with the tokens

I'm looking for token management options that handle react, react-native, ios and android. 
Our existing web and react native components are using styled-components with a shared json theme.

Diez seem to be so close to generate this as the tokens are already written in objects, right?

I also would like to know if you are planning on having React Native support. With a json output most of the web tokens would work, I believe that only a few properties would need changing (shadows for ex)

Thank you!

**Comment by roperzh** [comment]
Hey @arielwb , thanks for bringing this up! 

- **JSON** as a target is slated for the next upcoming version (`10.6.0`) and should be out next week, I will ping you then! I created https://github.com/diez/diez/issues/119 now to track JSON specifically
- **React Native** as a target is in our Roadmap (https://github.com/diez/diez/issues/22) we don't have an estimate yet for when it's coming, if you have any ideas or suggestions please add them to the issue!

I will close this in favor of the existent issues, but feel free to reach out if you have any more questions.
