### ISSUE TITLE
Add a Units prefab or export relative units for spacings

### ISSUE THREAD

**Issue by MarcelloDiSimone** [diez/diez#118]
Currently spacings are exported in different css units without taking into account the relative lengths of them. If I export a spacing object:

```typescript
 
const spacing = {
  sm: 8,
  md: 16,
  lg: 24
};
```
I will get a uniform set of values:

```scss
$spacing-sm: 8;
$spacing-sm-px: 8px;
$spacing-sm-pt: 8pt;
$spacing-sm-em: 8em;
$spacing-sm-rem: 8rem;
//...
```
Having 8em as your "small" value is very strange, rather should the output be (assuming pixel unit and 16px browser default font-size)

```scss
$spacing-sm: 8;
$spacing-sm-px: 8px;
$spacing-sm-pt: 6pt; // $spacing-sm * 0.75
$spacing-sm-em: .5em;  // $spacing-sm / 16
$spacing-sm-rem: .5rem; // $spacing-sm / 16
```
 However, calculating them automatically would need a way to define/change the default font-size and css unit to be used.

Another solution could be to add a Units prefab, like the following:

```typescript
const spacing = {
  sm: new Units().pixel(8), 
  md: new Units().em(1, 16), // Units(emValue: number, defaultFontSize?:number)
  lg: new Units().percent(120)
};
```
This would also open up the possibility to add more units like vh, vw and others without bloating up the stylesheet.

**Comment by zackbrown** [comment]
Hey @MarcelloDiSimone thanks for sharing your ideas here.  We've spun our wheels on the ideal design for `Unit-ed numbers` for a while, and have kept punting it as a result.

That said, that last suggestion of yours looks like a promising direction to me. I'm filing this into our Roadmap (https://github.com/diez/diez/projects/1) to evaluate priority for the next release or two.

If you're interested in contributing this yourself, let me know and we can help provide guidance or line up a kick-off call!
