### ISSUE TITLE
Error when running yarn demo

### ISSUE THREAD

**Issue by damianesteban** [diez/diez#12]
After creating a project and attempting to launch the demo app I get the following error:

`$ yarn demo`

```

ERROR in ./src/App.module.scss (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/sass-loader/dist/cjs.js!./src/App.module.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

  background-image: $palette-header-background;
                   ^
      Undefined variable: "$palette-header-background".
      in /Users/damianesteban/src/messaround/bpt-design/example-codebases/web/src/App.module.scss (line 21, column 21)
 @ ./src/App.module.scss 2:14-133 21:1-42:3 22:19-138
 @ ./src/App.jsx
 @ ./src/index.jsx
ℹ ｢wdm｣: Failed to compile.
```

**Comment by roperzh** [comment]
Hey @damianesteban , I'm very sorry you are experiencing this error, two things come into mind:

1. First, could you try again? We had some hiccups with the demo project this afternoon, but it should be working fine with version `10.0.2`. Running `yarn create diez projectname` again in a new folder should do it.
2. If you still have problems, could you share your node, yarn and OS versions? Thanks!

**Comment by damianesteban** [comment]
I upgraded to node v12.13.1 and its working perfectly. We are very excited to evaluate Diez.

Thank you.
