### ISSUE TITLE
Improve static docs

### ISSUE THREAD

**Issue by selique** [diez/diez#142]
I work with diez and when try to deploy my docs gen from Diez the folder assets don't include on folder dist this issue to deploy services like firebase hosting, and I wanna know which module doing for try fix this

**Comment by selique** [comment]
side effects like broken path images on static images (u can see example on https://superdigital-tokens-diez.web.app/#/DesignLanguage/logosComponents )

**Comment by selique** [comment]
i

**Comment by acespace90** [comment]
Hi, how do you solved? I'm in the same situation, I want to export docs and then deploy on a server.
