### ISSUE TITLE
Does diez support less?

### ISSUE THREAD

**Issue by arvinxx** [diez/diez#144]
I use less mostly.If diez support less ,it will be super great.

**Comment by roperzh** [comment]
Hey @arvinxx, it does not currently but indeed would be great to have. If anyone is interested it should be trivial to support, take a look at:

1. The Web compiler https://github.com/diez/diez/blob/d8c70ac27b130d217b60a7b919aef84b23936154/src/compiler/targets/src/targets/web.compiler.ts#L320-L339
2. The [CSS](https://github.com/diez/diez/blob/master/src/compiler/targets/sources/web/styles.css.handlebars) and [SCSS](https://github.com/diez/diez/blob/master/src/compiler/targets/sources/web/styles.scss.handlebars) templates.
