### ISSUE TITLE
SVG support (for web targets)

### ISSUE THREAD

**Issue by taylorpoe** [diez/diez#32]
For Figma & Sketch (and DSM) extract SVG when available, attach to Image prefabs, whitelist for web only, expose as .svg file

Re: consumption/declaration with Image prefab -- auto-magically discover presence of e.g. .png and .svg files from a string describing the file w/o extension

**Comment by dangodev** [comment]
+1 for this! Personally I’d like only an option to _only_ download SVGs, and not PNGs, if possible (currently in Figma I’m getting rate-limited, and it’s a lot of downloading/publishing to npm that we won’t use).
