### ISSUE TITLE
Support for NPM, in addition to Yarn

### ISSUE THREAD

**Issue by taylorpoe** [diez/diez#33]

**Comment by phil-lgr** [comment]
I don't have yarn installed at my workspace (bank) where every new tool needs to be validated.. please consider supporting npx / npm or publishing a diez cli on npm

**Comment by roperzh** [comment]
hey @phil-lgr ! we already support `npx/npm`, you should be able to run `npx diez create` and get started.

Are you having problems running that command? or the lack of documentation misguided you?

**Comment by phil-lgr** [comment]
Hi just saw https://medium.com/dieznative/diez-v10-2-is-out-86c675ebba4d super! thanks, just need to update the docs :)

https://diez.org/getting-started/#set-up

**Comment by roperzh** [comment]
Thanks for the feedback! we should update that page asap indeed.
