### ISSUE TITLE
add actual values to design system types

### ISSUE THREAD

**Issue by chrisdrackett** [diez/diez#47]
Right now if I mouse over something from my design system I get something like the following:

```
layoutValues.someHeight: number
```

It would be nice, as this is a constant to instead get:

```
layoutValues.someHeight: 30
```

same for colors and any other value really.

**Comment by zackbrown** [comment]
Hey @chrisdrackett this is a great idea.  

We've charted out a solution to this and it's prioritized for our current sprint.  Likely won't make the next Diez release (cutting today/tomorrow) but should make the following release.

**Comment by taylorpoe** [comment]
@chrisdrackett Hey just wanted to reach out and let you know this feature has been released!  https://medium.com/dieznative/contextual-documentation-for-design-tokens-e31d6d5e5489
