### ISSUE TITLE
Compile Option - ES Module

### ISSUE THREAD

**Issue by jeric17** [diez/diez#53]
Question: Is there a way to compile Diez to ES modules? Currently it only supports CommonJS.

**Comment by dangodev** [comment]
+1! It’d be awesome to be able to serve an ESM version via https://pika.dev/cdn or something.

**Comment by roperzh** [comment]
Hey folks! we merged #65 a couple of days ago.

Starting with next release, the output of compiling your design language for web with `diez compile --target web` will include an ES module wrapper + conditional exports in `package.json` as described [here](https://nodejs.org/api/esm.html#esm_approach_1_use_an_es_module_wrapper).

We understand that this will solve this particular issue, do you have any comments/suggestions? Any feedback is appreciated 🤗

**Comment by roperzh** [comment]
This is available from version `10.2.1`, let me know if you have feedback/ideas! closing for now.
