### ISSUE TITLE
EPERM: operation not permitted, scandir '[ ... ]\example-codebases\web\public\diez'

### ISSUE THREAD

**Issue by yuriybelike** [diez/diez#71]
Following the "Getting Started" steps, when executing
`yarn demo` the title's error shows up:

> PS C:\Users\user\Desktop\org\unocero\design-language> yarn demo 
> yarn run v1.22.0
> $ diez start web
> Building Diez project for target web...
> $ C:\Users\user\Desktop\org\unocero\design-language\node_modules\.bin\diez compile -t web
> Validating project structure at C:\Users\user\Desktop\org\unocero\design-language...
> Compiling project...
> Diez package compiled to C:\Users\user\Desktop\org\unocero\design-language\build\diez-unocero-web.
> 
> You can depend on Diez in package.json:
> 
>     {
>       "dependencies": {
>         "diez-unocero": "*"
>       }
>     }
>     
> You can use the variables and classes defined by Diez in your CSS or Sass styles.
>   CSS:  rule: var(--palette-content-background);
>   Sass: rule: $palette-content-background;
> 
> You can also use Diez with JavaScript to bootstrap any of the components defined in your project.
> 
>     new Diez(DesignLanguage).attach((component) => {
>       // ...
>     });
>     
> Starting the Diez hot server...
> Validating project structure at C:\Users\user\Desktop\org\unocero\design-language...
> Compiling project...
> Serving hot on port 8080.
> Built in 4439ms.
> 
> Your Diez project is now running in hot mode for web.
> 
> In hot mode, Diez observes and emits changes to your design language in real time.
> 
> To learn more, follow along with the guide at:
> 
>   https://diez.org/getting-started/javascript.html
> 
> $ webpack-dev-server
> Enabling hot mode with URL: http://172.28.67.32:8080
> i ｢wds｣: Project is running at http://localhost:8081/
> i ｢wds｣: webpack output is served from /
> i ｢wds｣: Content not from webpack is served from C:\Users\user\Desktop\org\unocero\example-codebases\web
> i ｢wdm｣: wait until bundle finished: /
> ‼ ｢copy-webpack-plugin｣: unable to locate 'public\diez' at 'C:\Users\user\Desktop\org\unocero\example-codebases\web\public\diez'
> glob error { [Error: EPERM: operation not permitted, scandir 'C:\Users\user\Desktop\org\unocero\example-codebases\web\public\diez']
>   errno: -4048,
>   code: 'EPERM',
>   syscall: 'scandir',
>   path:
>    'C:\\Users\\user\\Desktop\\org\\unocero\\example-codebases\\web\\public\\diez' }
> × ｢wdm｣: 
> ERROR in EPERM: operation not permitted, scandir 'C:\Users\user\Desktop\org\unocero\example-codebases\web\public\diez'
> i ｢wdm｣: Failed to compile.
> i ｢wdm｣: Compiling...
> ‼ ｢copy-webpack-plugin｣: unable to locate 'public\diez' at 'C:\Users\user\Desktop\org\unocero\example-codebases\web\public\diez'
> glob error { [Error: EPERM: operation not permitted, scandir 'C:\Users\user\Desktop\org\unocero\example-codebases\web\public\diez']
>   errno: -4048,
>   code: 'EPERM',
>   syscall: 'scandir',
>   path:
>    'C:\\Users\\user\\Desktop\\org\\unocero\\example-codebases\\web\\public\\diez' }
> × ｢wdm｣:
> ERROR in EPERM: operation not permitted, scandir 'C:\Users\user\Desktop\org\unocero\example-codebases\web\public\diez'
> i ｢wdm｣: Failed to compile.

The tab `http://localhost:8081/` opens up and shows the demo page, but hot reloading doesn't seem to be working because of the error.

**OS:** Windows 10 1909
**Diez:** 10.2.3
**Yarn:** 1.22.0
**Node:** 10.16.3

**Comment by yuriybelike** [comment]
Just tried to manually delete the `\example-codebases\web\public\diez` symlink file
and creating it via GUI. 
No error is thrown, only a warning `unable to locate public\diez`, but hot reloading seems to be working now.

**Comment by roperzh** [comment]
Thanks for the report and all the details!
