### ISSUE TITLE
Wrap token names with quotes

### ISSUE THREAD

**Issue by yuriybelike** [diez/diez#75]
When extracting from Figma (not sure if it happens with other tools too) the extracted tokens use the literal syntax for object property names, like:

```js
const figmaDesignSystemTemplateSetproductComCopyTypography = {
    10SpOverline: new Typograph({ fontSize: 10, color: Color.rgba(0, 0, 0, 0.8700000047683716), font: new Font({ name: "Roboto-Medium" }) }),
}
```

This throws an error for names that have leading numbers, illegal for JS identifiers.

How viable is to make the extractor to wrap all property names with quotes?

```js
const figmaDesignSystemTemplateSetproductComCopyTypography = {
    '10SpOverline': new Typograph({ fontSize: 10, color: Color.rgba(0, 0, 0, 0.8700000047683716), font: new Font({ name: "Roboto-Medium" }) }),
}
```

----

**Steps to reproduce**:

- Make Diez extract [https://www.figma.com/file/4FgwyPERZehFWdfy6HVpYL/Figma-design-system-template-setproduct.com/duplicate](https://www.figma.com/file/4FgwyPERZehFWdfy6HVpYL/Figma-design-system-template-setproduct.com/duplicate)
- Open `src/designs/FigmaDesignSystemTemplateSetproductComCopy.figma.ts` file

**Comment by roperzh** [comment]
As usual, thanks for the excellent report, @yuriybelike ! We are planning to ship a fix for this in the next release.
