### ISSUE TITLE
SyntaxError: Octal escape sequences are not allowed in strict mode

### ISSUE THREAD

**Issue by yuriybelike** [diez/diez#83]
Upon extracting a Figma project with components named as a number

https://www.figma.com/file/05DmUqhAmIA7GhRjgwqZa8/Diez-Issue-Report?node-id=0%3A1

![image](https://user-images.githubusercontent.com/60257988/75254680-ff8ddf00-57e0-11ea-9f02-7cdce576e227.png)

the generated file contains what seem to be invalid paths, that throw an error on compile:

```js
export const diezIssueReportComponentsFiles = {
    2: new File({ src: "assets\DiezIssueReport.figma.contents\components\2.png" }),
    '22x': new File({ src: "assets\DiezIssueReport.figma.contents\components\2@2x.png" }),
    '23x': new File({ src: "assets\DiezIssueReport.figma.contents\components\2@3x.png" }),
    '24x': new File({ src: "assets\DiezIssueReport.figma.contents\components\2@4x.png" })
};
```

> Compiling project...
> SyntaxError: Octal escape sequences are not allowed in strict mode.
> error Command failed with exit code 1.

### Step to reproduce
- Initialize diez as usual
- Add the linked Figma project to diezrc
- Extract
- Link the generated `diezIssueReportTokens` to the entrypoint
- Run `yarn diez compile`

-----

**OS:** Windows 10 1909
**Diez:** 10.3.0
**Yarn:** 1.22.0
**Node:** 10.16.3

**Comment by zackbrown** [comment]
@yuriybelike — thank you for the excellent bug report.  We were able to repro (Windows-specific, related to backslash paths) and shipped a fix for this to master earlier today: https://github.com/diez/diez/pull/84

This will make it out to npm when we release 10.4, which will be shipping in the coming weeks.  Closing this issue for now.

**Comment by zackbrown** [comment]
@yuriybelike — update: this fix shipped yesterday with our patch-release 10.3.1.

To upgrade an existing project, you can run:
```sh
# if using npm
npm install diez@latest

# if using yarn:
yarn upgrade diez --latest
```

**Comment by yuriybelike** [comment]
Rrunning into the same issue after upgrading. I'm guessing because the other diez packages, like the extractors one  aren't upgraded?

**Comment by zackbrown** [comment]
> I'm guessing because the other diez packages, like the extractors one aren't upgraded?

After running the upgrade, are you seeing the version 10.3.1 for `@diez/extractors` reflected in `yarn.lock` ?  

If not, can you try:
 - manually updating the versions in your package.json and running `yarn install` again, or
 - using a carat-prefixed syntax for versions (like `^10.0.0`) and running the `upgrade an existing project` command again (from previous comment)

After either of the above, you _should_ be able to see `10.3.1` reflected inside `yarn.lock`

If you can confirm the version upgrade but are still seeing the `octal escape sequence` error, one more thing to try:  see if this issue still occurs when using yarn 1.19.1.  You can do this very easily on a single project (will not affect the yarn version for other projects) using the command `yarn policies set-version 1.19.1`

If none of this helps, we'll re-open this issue and follow up to get some more info from you (as long as you're willing & able to keep helping!)

**Comment by yuriybelike** [comment]
Inside `yarn.lock` the extractors package was still at `.0`, had to run:

```bash
yarn upgrade diez @diez/engine @diez/prefabs @diez/compiler-core @diez/extractors @diez/start @diez/stdlib --latest
```

in order to upgrade all diez packages. After that, the issue went away.

**Comment by zackbrown** [comment]
Ah great, thank you for following up with that @yuriybelike and sorry for the incomplete upgrade instructions.  Glad to hear you're up and running.  I updated the script above for any future passers-by.

We're investigating a way to smooth this, possibly with a custom `diez upgrade` command.
