### ISSUE TITLE
Scaffolding does not create necessary package.json

### ISSUE THREAD

**Issue by derekatkinson** [diez/diez#94]
**Diez version:** 10.3.1

Following the steps for project setup on https://diez.org/getting-started/#set-up, anything I try to do thereafter (e.g. `npm run demo`, `npx diez extract`) fails because there is no package.json. This occurs when setting up the official template project via both `yarn create diez` and `npx diez create`. Am I missing an additional step, or is the scaffolding supposed to include a package.json and it is missing?

**Comment by roperzh** [comment]
hey @derekatkinson, I'm sorry to hear that you are having problems double checking before investigating further, `yarn create diez`  or `npx diez create` creates the following structure:

```
example-project/
├── README.md
├── design-language
│   ├── assets
│   ├── designs
│   ├── src
│   ├── tsconfig.json
│   ├── tslint.json
│   └── package.json
└── example-codebases
    ├── android
    ├── ios
    └── web
```

You need to be in the `design-language` directory  (`cd project-name/design-language`) to be able to run `npx diez extract`, are you in `design-language`?

**Comment by derekatkinson** [comment]
Right you are @roperzh , thanks. I missed that part and, because I ran into other errors when trying to `npx diez extract` while in the `design-language` directory, I assumed that wasn't the package.json it was looking for.

I'm able to `npm run demo` successfully now, but have problems with `npx diez extract`. Since that's a different issue, I'll close this and create a separate issue to share the details of that issue.

**Comment by roperzh** [comment]
thanks for the follow up! and thanks for the willingness to report the extract issue you are having, I hope we can solve that one quickly too.
