### ISSUE TITLE
npx diez extract: fails with spaces in file name, partially fails otherwise

### ISSUE THREAD

**Issue by derekatkinson** [diez/diez#95]
**Diez version:** 10.3.1

# Issue 1
While in the `design-language` directory, I tried running `npx diez extract` with a Sketch file named `COMMON color system.sketch` in the `designs` directory. This failed, telling me a few times:
```
Creating necessary folders for CommonColorSystem.sketch
Running sketchtool export commands for CommonColorSystem.sketch
Error: Command failed: /Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool dump /Users/a9f0bzz/source/_diez-test/aura-diez/design-language/designs/COMMON color system.sketch
The file doesn’t exist.

(NSCocoaErrorDomain:4)
```

I noticed that it was trying to work with a file named `CommonColorSystem.sketch` (my filename converted to Pascal case), so I removed the spaces and that particular error stopped.

# Issue 2
While in the `design-language` directory, I tried running `npx diez extract` with a Sketch file named `commoncolorsystem.sketch` in the `designs` directory. This **partially** failed, telling me:

```
Creating necessary folders for Commoncolorsystem.sketch
Running sketchtool export commands for Commoncolorsystem.sketch
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
```

After this task finished (npx showed no indication aside from returning me to the command prompt after a delay, but yarn told me it was "✨  Done in 16.27s."):
* Slice exports show up in `assets/CommonColorSystem.sketch.contents/slices` as expected.
* **There is no `src/designs` folder.**

**Comment by roperzh** [comment]
@derekatkinson thanks for the wonderful report, I will take this and will be fixed in the upcoming release.

**Comment by roperzh** [comment]
thanks again for the report, both issues have been fixed and will be part of the next release, I will be sure to ping you when it goes out!

**Comment by derekatkinson** [comment]
Thanks, @roperzh !
